
package com.senyastr.stockweb.models;
public enum MessageClass{
    USER_INTERACTION_NEEDED,
    CONTACT,
    DATASET_SEARCH,
    DELIVERY,
    ORDER,
    WELCOME,
    FEEDBACK_POSITIVE,
    FEEDBACK_NEGATIVE,
    FEEDBACK_NEUTRAL,
    CHECKOUT,
    CHECKOUT_REQUEST,
    RECOMMENDATION
}
